version: "3"
services:
  api:
    container_name: api
    build:
        dockerfile: Dockerfile
        context: .
    ports: 
        - "8000:8000"
    restart: on-failure
    volumes:
        - api:/usr/src/app/
    depends_on:
        - db
    deploy:
        replicas: 5

  db:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
        - '5432:5432'
    environment:
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST} 
    volumes:
        - database_postgres:/var/lib/postgresql/data

      
volumes:
    api:
    database_postgres: 
        
# Networks to be created to facilitate communication between containers
networks:
    champay-network:
      driver: bridge
    
    

 
    
  
