version: "3"
services:
  champay-backend:
    container_name: "champay-backend"
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: python wsgi.py
    volumes:
      - .:/code
    
    

 
    
  
